#include <cstdint>
#include <cstdio>
#include <vector>
#include <string>
#include <cassert>
#include <array>

using namespace std;

#define ENABLE_DPRINTF (1)
#define ENABLE_ASSERT (1)

#if ENABLE_DPRINTF
#define DPRINTF(...) \
do { \
    printf("L%d %s(): ", __LINE__, __func__); \
    printf(__VA_ARGS__); \
} while (false)
#else
#define DPRINTF(...)
#endif // #if ENABLE_DPRINTF

#if ENABLE_ASSERT
#define ASSERT(...) assert(__VA_ARGS__)
#else
#define ASSERT(...)
#endif // #if ENABLE_ASSERT

struct Coord
{
    Coord(int32_t x, int32_t y) : m_x(x), m_y(y) {}
    int32_t m_x = 0;
    int32_t m_y = 0;
};

vector<Coord> getCoords(const vector<vector<char>>& board, const char c)
{
    vector<Coord> coords;

    for (int32_t y = 0; y < board.size(); ++y)
    {
        for (int32_t x = 0; x < board.at(y).size(); ++x)
        {
            if (board.at(y).at(x) == c)
            {
                coords.emplace_back(Coord(x, y));
            }
        }
    }

    return coords;
}

class Solution {
public:
    vector<string> findWords(vector<vector<char>>& board, vector<string>& words) {

        vector<string> ans;

        for (const string& word : words)
        {
            ASSERT(word.length() > 0);

            const vector<Coord> coords = getCoords(board, word.at(0));

            for (const Coord coord : coords)
            {
                if (findWordsRecursively(board, word, 1, coord))
                {
                    ans.emplace_back(word);
                    break;
                }
            }
        }

        return ans;
    }

private:
    bool isOutOfBound(int32_t width, int32_t height, Coord current, Coord shift)
    {
        const Coord next_coord(current.m_x + shift.m_x, current.m_y + shift.m_y);

        if (next_coord.m_x < 0 || width <= next_coord.m_x)
            return true;
        
        if (next_coord.m_y < 0 || height <= next_coord.m_y)
            return true;

        return false;
    }

    bool findWordsRecursively(vector<vector<char>> board, const string& word, int32_t pos, Coord coord)
    {
        if (word.size() == pos)
            return true;

        // mark the coord as already visited
        board.at(coord.m_y).at(coord.m_x) = '_';

        const array<Coord, 4> next_shift = {Coord(-1, 0), Coord(1, 0), Coord(0, -1), Coord(0, 1)};

        for (Coord shift : next_shift)
        {
            if (isOutOfBound(board.at(0).size(), board.size(), coord, shift))
                continue;

            const Coord next_coord(coord.m_x + shift.m_x, coord.m_y + shift.m_y);

            if (word.at(pos) != board.at(next_coord.m_y).at(next_coord.m_x))
                continue;
            
            if (findWordsRecursively(board, word, pos + 1, next_coord))
                return true;
        }

        return false;
    }
};

void check(vector<string> strs0, vector<string> strs1)
{
    std::sort(strs0.begin(), strs0.end());
    std::sort(strs1.begin(), strs1.end());
    ASSERT(strs0 == strs1);
}

int32_t main(int32_t argc, char* argv[])
{
    vector<vector<char>> board;
    vector<string> words;
    vector<string> exp;
    vector<string> ans;

    {
        board = {{'o', 'a', 'a', 'n'}, {'e', 't', 'a', 'e'}, {'i', 'h', 'k', 'r'}, {'i', 'f', 'l', 'v'}};
        words = {"oath", "pea", "eat", "rain"};
        exp = {"eat","oath"};

        Solution solution;
        ans = solution.findWords(board, words); check(ans, exp);
    }

    {
        board = {{'a','b'},{'c','d'}};
        words = {"abcb"};
        exp = { };

        Solution solution;
        ans = solution.findWords(board, words); check(ans, exp);
    }

    {
        // TODO: perf optimization
        board = {{'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a'},
                 {'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'},
                 {'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a'},
                 {'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'},
                 {'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a'},
                 {'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'},
                 {'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a'},
                 {'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'},
                 {'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a'},
                 {'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b', 'a', 'b'}};

        words = {
            "ababababaa",
            "ababababab",
            "ababababac",
            "ababababad",
            "ababababae",
            "ababababaf",
            "ababababag",
            "ababababah",
            "ababababai",
            "ababababaj",
            "ababababak",
            "ababababal",
            "ababababam",
            "ababababan",
            "ababababao",
            "ababababap",
            "ababababaq",
            "ababababar",
            "ababababas",
            "ababababat",
            "ababababau",
            "ababababav",
            "ababababaw",
            "ababababax",
            "ababababay",
            "ababababaz",
            "ababababba",
            "ababababbb",
            "ababababbc",
            "ababababbd",
            "ababababbe",
            "ababababbf",
            "ababababbg",
            "ababababbh",
            "ababababbi",
            "ababababbj",
            "ababababbk",
            "ababababbl",
            "ababababbm",
            "ababababbn",
            "ababababbo",
            "ababababbp",
            "ababababbq",
            "ababababbr",
            "ababababbs",
            "ababababbt",
            "ababababbu",
            "ababababbv",
            "ababababbw",
            "ababababbx",
            "ababababby",
            "ababababbz",
            "ababababca",
            "ababababcb",
            "ababababcc",
            "ababababcd",
            "ababababce",
            "ababababcf",
            "ababababcg",
            "ababababch",
            "ababababci",
            "ababababcj",
            "ababababck",
            "ababababcl",
            "ababababcm",
            "ababababcn",
            "ababababco",
            "ababababcp",
            "ababababcq",
            "ababababcr",
            "ababababcs",
            "ababababct",
            "ababababcu",
            "ababababcv",
            "ababababcw",
            "ababababcx",
            "ababababcy",
            "ababababcz",
            "ababababda",
            "ababababdb",
            "ababababdc",
            "ababababdd",
            "ababababde",
            "ababababdf",
            "ababababdg",
            "ababababdh",
            "ababababdi",
            "ababababdj",
            "ababababdk",
            "ababababdl",
            "ababababdm",
            "ababababdn",
            "ababababdo",
            "ababababdp",
            "ababababdq",
            "ababababdr",
            "ababababds",
            "ababababdt",
            "ababababdu",
            "ababababdv",
            "ababababdw",
            "ababababdx",
            "ababababdy",
            "ababababdz",
            "ababababea",
            "ababababeb",
            "ababababec",
            "ababababed",
            "ababababee",
            "ababababef",
            "ababababeg",
            "ababababeh",
            "ababababei",
            "ababababej",
            "ababababek",
            "ababababel",
            "ababababem",
            "ababababen",
            "ababababeo",
            "ababababep",
            "ababababeq",
            "ababababer",
            "ababababes",
            "ababababet",
            "ababababeu",
            "ababababev",
            "ababababew",
            "ababababex",
            "ababababey",
            "ababababez",
            "ababababfa",
            "ababababfb",
            "ababababfc",
            "ababababfd",
            "ababababfe",
            "ababababff",
            "ababababfg",
            "ababababfh",
            "ababababfi",
            "ababababfj",
            "ababababfk",
            "ababababfl",
            "ababababfm",
            "ababababfn",
            "ababababfo",
            "ababababfp",
            "ababababfq",
            "ababababfr",
            "ababababfs",
            "ababababft",
            "ababababfu",
            "ababababfv",
            "ababababfw",
            "ababababfx",
            "ababababfy",
            "ababababfz",
            "ababababga",
            "ababababgb",
            "ababababgc",
            "ababababgd",
            "ababababge",
            "ababababgf",
            "ababababgg",
            "ababababgh",
            "ababababgi",
            "ababababgj",
            "ababababgk",
            "ababababgl",
            "ababababgm",
            "ababababgn",
            "ababababgo",
            "ababababgp",
            "ababababgq",
            "ababababgr",
            "ababababgs",
            "ababababgt",
            "ababababgu",
            "ababababgv",
            "ababababgw",
            "ababababgx",
            "ababababgy",
            "ababababgz",
            "ababababha",
            "ababababhb",
            "ababababhc",
            "ababababhd",
            "ababababhe",
            "ababababhf",
            "ababababhg",
            "ababababhh",
            "ababababhi",
            "ababababhj",
            "ababababhk",
            "ababababhl",
            "ababababhm",
            "ababababhn",
            "ababababho",
            "ababababhp",
            "ababababhq",
            "ababababhr",
            "ababababhs",
            "ababababht",
            "ababababhu",
            "ababababhv",
            "ababababhw",
            "ababababhx",
            "ababababhy",
            "ababababhz",
            "ababababia",
            "ababababib",
            "ababababic",
            "ababababid",
            "ababababie",
            "ababababif",
            "ababababig",
            "ababababih",
            "ababababii",
            "ababababij",
            "ababababik",
            "ababababil",
            "ababababim",
            "ababababin",
            "ababababio",
            "ababababip",
            "ababababiq",
            "ababababir",
            "ababababis",
            "ababababit",
            "ababababiu",
            "ababababiv",
            "ababababiw",
            "ababababix",
            "ababababiy",
            "ababababiz",
            "ababababja",
            "ababababjb",
            "ababababjc",
            "ababababjd",
            "ababababje",
            "ababababjf",
            "ababababjg",
            "ababababjh",
            "ababababji",
            "ababababjj",
            "ababababjk",
            "ababababjl",
            "ababababjm",
            "ababababjn",
            "ababababjo",
            "ababababjp",
            "ababababjq",
            "ababababjr",
            "ababababjs",
            "ababababjt",
            "ababababju",
            "ababababjv",
            "ababababjw",
            "ababababjx",
            "ababababjy",
            "ababababjz",
            "ababababka",
            "ababababkb",
            "ababababkc",
            "ababababkd",
            "ababababke",
            "ababababkf",
            "ababababkg",
            "ababababkh",
            "ababababki",
            "ababababkj",
            "ababababkk",
            "ababababkl",
            "ababababkm",
            "ababababkn",
            "ababababko",
            "ababababkp",
            "ababababkq",
            "ababababkr",
            "ababababks",
            "ababababkt",
            "ababababku",
            "ababababkv",
            "ababababkw",
            "ababababkx",
            "ababababky",
            "ababababkz",
            "ababababla",
            "abababablb",
            "abababablc",
            "ababababld",
            "abababable",
            "abababablf",
            "abababablg",
            "abababablh",
            "ababababli",
            "abababablj",
            "abababablk",
            "ababababll",
            "abababablm",
            "ababababln",
            "abababablo",
            "abababablp",
            "abababablq",
            "abababablr",
            "ababababls",
            "abababablt",
            "abababablu",
            "abababablv",
            "abababablw",
            "abababablx",
            "abababably",
            "abababablz",
            "ababababma",
            "ababababmb",
            "ababababmc",
            "ababababmd",
            "ababababme",
            "ababababmf",
            "ababababmg",
            "ababababmh",
            "ababababmi",
            "ababababmj",
            "ababababmk",
            "ababababml",
            "ababababmm",
            "ababababmn",
            "ababababmo",
            "ababababmp",
            "ababababmq",
            "ababababmr",
            "ababababms",
            "ababababmt",
            "ababababmu",
            "ababababmv",
            "ababababmw",
            "ababababmx",
            "ababababmy",
            "ababababmz",
            "ababababna",
            "ababababnb",
            "ababababnc",
            "ababababnd",
            "ababababne",
            "ababababnf",
            "ababababng",
            "ababababnh",
            "ababababni",
            "ababababnj",
            "ababababnk",
            "ababababnl",
            "ababababnm",
            "ababababnn",
            "ababababno",
            "ababababnp",
            "ababababnq",
            "ababababnr",
            "ababababns",
            "ababababnt",
            "ababababnu",
            "ababababnv",
            "ababababnw",
            "ababababnx",
            "ababababny",
            "ababababnz",
            "ababababoa",
            "ababababob",
            "ababababoc",
            "ababababod",
            "ababababoe",
            "ababababof",
            "ababababog",
            "ababababoh",
            "ababababoi",
            "ababababoj",
            "ababababok",
            "ababababol",
            "ababababom",
            "ababababon",
            "ababababoo",
            "ababababop",
            "ababababoq",
            "ababababor",
            "ababababos",
            "ababababot",
            "ababababou",
            "ababababov",
            "ababababow",
            "ababababox",
            "ababababoy",
            "ababababoz",
            "ababababpa",
            "ababababpb",
            "ababababpc",
            "ababababpd",
            "ababababpe",
            "ababababpf",
            "ababababpg",
            "ababababph",
            "ababababpi",
            "ababababpj",
            "ababababpk",
            "ababababpl",
            "ababababpm",
            "ababababpn",
            "ababababpo",
            "ababababpp",
            "ababababpq",
            "ababababpr",
            "ababababps",
            "ababababpt",
            "ababababpu",
            "ababababpv",
            "ababababpw",
            "ababababpx",
            "ababababpy",
            "ababababpz",
            "ababababqa",
            "ababababqb",
            "ababababqc",
            "ababababqd",
            "ababababqe",
            "ababababqf",
            "ababababqg",
            "ababababqh",
            "ababababqi",
            "ababababqj",
            "ababababqk",
            "ababababql",
            "ababababqm",
            "ababababqn",
            "ababababqo",
            "ababababqp",
            "ababababqq",
            "ababababqr",
            "ababababqs",
            "ababababqt",
            "ababababqu",
            "ababababqv",
            "ababababqw",
            "ababababqx",
            "ababababqy",
            "ababababqz",
            "ababababra",
            "ababababrb",
            "ababababrc",
            "ababababrd",
            "ababababre",
            "ababababrf",
            "ababababrg",
            "ababababrh",
            "ababababri",
            "ababababrj",
            "ababababrk",
            "ababababrl",
            "ababababrm",
            "ababababrn",
            "ababababro",
            "ababababrp",
            "ababababrq",
            "ababababrr",
            "ababababrs",
            "ababababrt",
            "ababababru",
            "ababababrv",
            "ababababrw",
            "ababababrx",
            "ababababry",
            "ababababrz",
            "ababababsa",
            "ababababsb",
            "ababababsc",
            "ababababsd",
            "ababababse",
            "ababababsf",
            "ababababsg",
            "ababababsh",
            "ababababsi",
            "ababababsj",
            "ababababsk",
            "ababababsl",
            "ababababsm",
            "ababababsn",
            "ababababso",
            "ababababsp",
            "ababababsq",
            "ababababsr",
            "ababababss",
            "ababababst",
            "ababababsu",
            "ababababsv",
            "ababababsw",
            "ababababsx",
            "ababababsy",
            "ababababsz",
            "ababababta",
            "ababababtb",
            "ababababtc",
            "ababababtd",
            "ababababte",
            "ababababtf",
            "ababababtg",
            "ababababth",
            "ababababti",
            "ababababtj",
            "ababababtk",
            "ababababtl",
            "ababababtm",
            "ababababtn",
            "ababababto",
            "ababababtp",
            "ababababtq",
            "ababababtr",
            "ababababts",
            "ababababtt",
            "ababababtu",
            "ababababtv",
            "ababababtw",
            "ababababtx",
            "ababababty",
            "ababababtz",
            "ababababua",
            "ababababub",
            "ababababuc",
            "ababababud",
            "ababababue",
            "ababababuf",
            "ababababug",
            "ababababuh",
            "ababababui",
            "ababababuj",
            "ababababuk",
            "ababababul",
            "ababababum",
            "ababababun",
            "ababababuo",
            "ababababup",
            "ababababuq",
            "ababababur",
            "ababababus",
            "ababababut",
            "ababababuu",
            "ababababuv",
            "ababababuw",
            "ababababux",
            "ababababuy",
            "ababababuz",
            "ababababva",
            "ababababvb",
            "ababababvc",
            "ababababvd",
            "ababababve",
            "ababababvf",
            "ababababvg",
            "ababababvh",
            "ababababvi",
            "ababababvj",
            "ababababvk",
            "ababababvl",
            "ababababvm",
            "ababababvn",
            "ababababvo",
            "ababababvp",
            "ababababvq",
            "ababababvr",
            "ababababvs",
            "ababababvt",
            "ababababvu",
            "ababababvv",
            "ababababvw",
            "ababababvx",
            "ababababvy",
            "ababababvz",
            "ababababwa",
            "ababababwb",
            "ababababwc",
            "ababababwd",
            "ababababwe",
            "ababababwf",
            "ababababwg",
            "ababababwh",
            "ababababwi",
            "ababababwj",
            "ababababwk",
            "ababababwl",
            "ababababwm",
            "ababababwn",
            "ababababwo",
            "ababababwp",
            "ababababwq",
            "ababababwr",
            "ababababws",
            "ababababwt",
            "ababababwu",
            "ababababwv",
            "ababababww",
            "ababababwx",
            "ababababwy",
            "ababababwz",
            "ababababxa",
            "ababababxb",
            "ababababxc",
            "ababababxd",
            "ababababxe",
            "ababababxf",
            "ababababxg",
            "ababababxh",
            "ababababxi",
            "ababababxj",
            "ababababxk",
            "ababababxl",
            "ababababxm",
            "ababababxn",
            "ababababxo",
            "ababababxp",
            "ababababxq",
            "ababababxr",
            "ababababxs",
            "ababababxt",
            "ababababxu",
            "ababababxv",
            "ababababxw",
            "ababababxx",
            "ababababxy",
            "ababababxz",
            "ababababya",
            "ababababyb",
            "ababababyc",
            "ababababyd",
            "ababababye",
            "ababababyf",
            "ababababyg",
            "ababababyh",
            "ababababyi",
            "ababababyj",
            "ababababyk",
            "ababababyl",
            "ababababym",
            "ababababyn",
            "ababababyo",
            "ababababyp",
            "ababababyq",
            "ababababyr",
            "ababababys",
            "ababababyt",
            "ababababyu",
            "ababababyv",
            "ababababyw",
            "ababababyx",
            "ababababyy",
            "ababababyz",
            "ababababza",
            "ababababzb",
            "ababababzc",
            "ababababzd",
            "ababababze",
            "ababababzf",
            "ababababzg",
            "ababababzh",
            "ababababzi",
            "ababababzj",
            "ababababzk",
            "ababababzl",
            "ababababzm",
            "ababababzn",
            "ababababzo",
            "ababababzp",
            "ababababzq",
            "ababababzr",
            "ababababzs",
            "ababababzt",
            "ababababzu",
            "ababababzv",
            "ababababzw",
            "ababababzx",
            "ababababzy",
            "ababababzz"
        };
        exp = { };

        Solution solution;
        ans = solution.findWords(board, words); check(ans, exp);
    }

    return 0;
}